site_name: Cours de M. Ricart
site_url: https://thomasricart.github.io

theme:
  name: material
  language: fr
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - search.suggest

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - _environments/javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - _environments/stylesheets/extra.css

exclude_docs: |
  # Fichiers sources et temporaires
  **/*.tex
  **/Images/*
  **/Sources_Latex/*
  _*/
  **/_*

  # Dossiers ignorés pour le moment (compilation CIEL2 uniquement)
  CIEL1/
  Maths_Premiere/
  NSI_Premiere/
  NSI_Terminale/
  SNT/