site_name: Cours de M. Ricart
site_url: https://thomasricart.github.io

theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - search.suggest

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - _environments/javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - _environments/stylesheets/extra.css
