site_name: Cours de M. Ricart
site_url: https://thomasricart.github.io

theme:
  name: material
  language: fr
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    - navigation.indexes
    - search.suggest
    # - toc.integrate   # <-- AJOUTER CETTE LIGNE

use_directory_urls: false

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - environments/javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - environments/stylesheets/extra.css

extra:
  generator: false

exclude_docs: |
  # 1. On ignore tout par défaut
  *

  # 2. On inclut uniquement la racine et les assets généraux
  !index.md
  !.pages
  !environments/**
  !graphics/**
  !scripts/**

  # 3. On inclut EXCLUSIVEMENT tes 3 dossiers cibles
  !CIEL2/**
  !NSI_Premiere/**
  !NSI_Terminale/**

  # 4. Exclusions spécifiques dans ces 3 dossiers
  **/*.tex
  **/Sources_Latex/*
  _*/
  **/_*